// packages/game-react/src/components/SliderGame.tsx
import { useGameStore } from '../stores/gameStore'
import { useGameLoop } from '../hooks/useGameLoop'
import { getScoreRating } from '@quicky-finger/shared'

interface Props {
  onScoreSubmit: (score: number) => void
}

export function SliderGame({ onScoreSubmit }: Props) {
  const { 
    isPlaying, 
    sliderPosition,
    currentScore, 
    bestScore,
    hasScore,
    startGame, 
    stopGame, 
    resetGame 
  } = useGameStore()

  const { direction } = useGameLoop()
  useGameLoop()

  const handleStart = () => {
    startGame()
  }

  const handleStop = () => {
    console.log('Stopping.. | Score:', useGameStore.getState().currentScore)
    stopGame()
    if (currentScore !== null) {
      onScoreSubmit(currentScore)
    }
  }

  const handlePlayAgain = () => {
    resetGame()
    startGame()
  }

  return (
    <div className="game-container max-w-sm sm:max-w-4xl w-full mx-auto">
      {/* Game Title */}
      <div className="text-center mb-8">
        <h1 className="text-5xl sm:text-7xl xl:text-9xl px-1 font-bold mb-2 max-w-max text-silver press-start-2p flicker">Quicky Finger</h1>
        <p className="text-gray-400">Stop the slider as close to center as possible!</p>
      </div>

      {/* FPS */}
      <div className="fps-counter fixed top-4 left-4 text-sm text-gray-400 mt-2">
        FPS:
        <span className="font-mono">
          `${0 || "--"} / ${0 || "--"}`
        </span>
      </div>

      {/* Best Score */}
      {bestScore > 0 && (
        <div className="text-center mb-4">
          <p className="text-sm text-gray-400">
            Best Score: <span className="text-yellow-400 font-bold">{bestScore}</span>
          </p>
        </div>
      )}

      {/* Game Area */}
      <div className="rounded-xl p-2 md:p-8 shadow-2xl game-area">
        
        {/* Slider Track */}
        {isPlaying && (
          <div className="mb-8">
            <div className="relative h-40 rounded-lg overflow-hidden max-w-full">
              {/* Target line */}
              <div 
                className="absolute top-0 bottom-0 w-1" 
                style={{ left: '50%',
                         transform: 'translateX(-50%)',
                         backgroundColor: 'var(--color-gold)' }}
              />
              
              {/* Moving slider */}
              <div 
                className={"slider absolute top-0 bottom-0 w-2 rounded transition-transform " + (direction.current == 1 ? 'right' : 'left')}
                style={{ 
                  left: `${sliderPosition}%`,
                  transform: 'translateX(-50%)',
                  willChange: 'transform',
                  backgroundColor: 'var(--color-success)'
                }}
              />
            </div>
            
            <div className="text-center mt-2 text-gray-400 text-sm">
              Position: {Math.round(sliderPosition)}%
            </div>
          </div>
        )}

        {/* Buttons */}
        <div className="flex justify-center gap-4 h-full">
          {!isPlaying && !hasScore() && (
            <button 
              onClick={handleStart}
              className="btn btn-primary start-btn press-start-2p pulse-btn"
            >
              Start Game
            </button>
          )}

          {isPlaying && (
            <button 
              onClick={handleStop}
              className="btn btn-danger stop-btn animate-pulse stop-button-shake press-start-2p"
            >
              STOP!
            </button>
          )}
        </div>

        {/* Score Display */}
        {hasScore() && currentScore !== null && (
          <div className="text-center mt-8">
            <div className="mb-6">
              <p className="text-6xl font-bold text-primary mb-2">
                {currentScore}
              </p>
              <p className="text-2xl text-gray-300">
                {getScoreRating(currentScore)}
              </p>
            </div>

            <div className="text-gray-400 mb-6">
              <p>Final Position: {Math.round(sliderPosition)}%</p>
              <p>Distance from Center: {Math.abs(Math.round(sliderPosition - 50))}%</p>
            </div>

            <button 
              onClick={handlePlayAgain}
              className="px-8 py-3 bg-success hover:bg-green-600 text-white text-xl font-semibold rounded-lg transition-all"
            >
              🔄 Play Again
            </button>
          </div>
        )}
      </div>

      {/* Instructions */}
      <div className="text-center mt-8 text-gray-500 text-sm">
        <p>🎯 Perfect center (50%) = 1000 points</p>
        <p>📉 Every 1% away = -20 points</p>
      </div>
    </div>
  )
}

// game-vue/src/components/SliderGame.vue
<script setup lang="ts">
import { ref, onUnmounted } from 'vue'
import { useGameStore } from '../stores/gameStore'
// import { useLeaderboardStore } from '../stores/leaderboardStore'
import { getScoreRating } from '../utils/scoring'

// Props - accept WebSocket submit function
const props = defineProps<{
  onScoreSubmit: (score: number) => Promise<void> | void
}>()

const gameStore = useGameStore()
// const leaderboardStore = useLeaderboardStore()
const animationFrameId = ref<number | null>(null)
const startTime = ref<number>(0)

// Game configuration
const CYCLE_DURATION = 2000 // 2 seconds for full left-right cycle

function startGame() {
  gameStore.startGame()
  startTime.value = performance.now()
  animate()
}

function animate() {
  const currentTime = performance.now()
  const elapsed = currentTime - startTime.value

  // Calculate position using sine wave (smooth oscillation)
  const progress = (elapsed % CYCLE_DURATION) / CYCLE_DURATION
  const position = 50 + 50 * Math.sin(progress * Math.PI * 2)

  gameStore.updatePosition(position)

  // Continue animation if game is still playing
  if (gameStore.isPlaying) {
    animationFrameId.value = requestAnimationFrame(animate)
  }
}

async function stopGame() {
	if (animationFrameId.value) {
		cancelAnimationFrame(animationFrameId.value)
		animationFrameId.value = null
	}
	gameStore.stopGame()

	// Submit score via WebSocket
	if (gameStore.currentScore !== null) {
		// props.onScoreSubmit(gameStore.currentScore)
		try {
			await props.onScoreSubmit(gameStore.currentScore)
		} catch (error) {
			console.error('Error submitting score:', error)
		}
	}
}

function playAgain() {
  gameStore.resetGame()
  startGame()
}

// Cleanup on component unmount
onUnmounted(() => {
  if (animationFrameId.value) {
    cancelAnimationFrame(animationFrameId.value)
  }
})
</script>

<template>
	<div class="game-container max-w-2xl w-full mx-auto">
		<!-- Game Title -->
		<div class="text-center mb-8">
			<h1 class="text-5xl font-bold mb-2">Quicky Finger</h1>
			<p class="text-gray-400">Stop the slider as close to center as possible!</p>
		</div>

		<!-- Best Score Display -->
		<div v-if="gameStore.bestScore > 0" class="text-center mb-4">
			<p class="text-sm text-gray-400">
				Best Score: <span class="text-yellow-400 font-bold">{{ gameStore.bestScore }}</span>
			</p>
		</div>

		<!-- Game Area -->
		<div class="bg-gray-800 rounded-xl p-8 shadow-2xl">
			<!-- Slider Track (only shown when playing) -->
			<div v-if="gameStore.isPlaying" class="mb-8">
				<div class="relative h-24 bg-gray-700 rounded-lg overflow-hidden">
					<!-- Target line (center) -->
					<div class="absolute top-0 bottom-0 w-1 bg-green-400" style="left: 50%; transform: translateX(-50%)"></div>

					<!-- Moving slider indicator -->
					<div
						class="absolute top-0 bottom-0 w-4 bg-primary rounded transition-transform"
						:style="{ 
              left: gameStore.sliderPosition + '%',
              transform: 'translateX(-50%)',
              willChange: 'transform'
            }"
					></div>
				</div>

				<!-- Position indicator -->
				<div class="text-center mt-2 text-gray-400 text-sm">Position: {{ Math.round(gameStore.sliderPosition) }}%</div>
			</div>

			<!-- Control Buttons -->
			<div class="flex justify-center gap-4">
				<!-- Start Button -->
				<button v-if="!gameStore.isPlaying && !gameStore.hasScore" @click="startGame" class="btn btn-primary text-2xl px-12 py-4">Start Game</button>

				<!-- Stop Button -->
				<button v-if="gameStore.isPlaying" @click="stopGame" class="btn btn-danger text-3xl px-16 py-6 animate-pulse">STOP!</button>
			</div>

			<!-- Score Display -->
			<div v-if="gameStore.hasScore" class="text-center mt-8">
				<div class="mb-6">
					<p class="text-6xl font-bold text-primary mb-2">
						{{ gameStore.currentScore }}
					</p>
					<p class="text-2xl text-gray-300">
						{{ getScoreRating(gameStore.currentScore!) }}
					</p>
				</div>

				<div class="text-gray-400 mb-6">
					<p>Final Position: {{ Math.round(gameStore.sliderPosition) }}%</p>
					<p>Distance from Center: {{ Math.abs(Math.round(gameStore.sliderPosition - 50)) }}%</p>
				</div>

				<button @click="playAgain" class="btn btn-success text-xl px-8 py-3">Play Again</button>
			</div>
		</div>

		<!-- Instructions -->
		<div class="text-center mt-8 text-gray-500 text-sm">
			<p>Perfect center (50%) = 1000 points</p>
			<p>Every 1% away = -20 points</p>
		</div>
	</div>
</template>

<style scoped>
.game-container {
  animation: fadeIn 0.5s ease-in;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(-20px); }
  to { opacity: 1; transform: translateY(0); }
}
</style>
